# -*- coding: utf-8 -*-
"""Calculadora basica

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YczPkpVOJsZl0J2shS1zc-OV46eYzlVo
"""

def suma(num1, num2):
  res = num1 + num2
  return(res)

def resta(num1, num2):
  res = num1 - num2
  return(res)

def multi(num1, num2):
  res = num1*num2
  return(res)

def division(num1, num2):
  if num2 == 0:
   while num2 == 0:
    print("No se puede dividir por 0, repitalo")
    num2 = int(input())
  res = num1/num2
  return(res)

decision = 0

while decision != 5:
 print("""Elija una de las opciones: 1. suma
                                     2. resta
                                     3. multiplicacion
                                     4. division
                                     5. salir""")
 decision = int(input())

 if decision == 1 or decision == 2 or decision == 3 or decision == 4:
  Numero1 = int(input("Ingrese un numero: "))
  Numero2 = int(input("Ingrese otro numero: "))

 if decision == 1:
  print("El resultado de la suma es: ",suma(Numero1,Numero2))

 elif decision == 2:
  print("El resultado de la resta es: ",resta(Numero1,Numero2))

 elif decision == 3:
  print("El resultado de la multiplicacion es: ",multi(Numero1,Numero2))

 elif decision == 4:
  print("El resultado de la division es: ",division(Numero1,Numero2))

 elif decision == 5:
  break
  +
 else:
  print("ingrese un valor correcto.")